packages

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -12,18 +12,14 @@ phases:
     commands:
       - echo "Empaquetando función Lambda: $LAMBDA_FUNCTION_NAME"
       - mkdir -p dist
-
-      # Verifica que exista la carpeta correspondiente a la Lambda
-      - if [ ! -d "$LAMBDA_FUNCTION_NAME" ]; then
-          echo "Error No existe el directorio $LAMBDA_FUNCTION_NAME";
-          exit 1;
+      - |
+        if [ ! -d "$LAMBDA_FUNCTION_NAME" ]; then
+          echo "Error: No existe el directorio $LAMBDA_FUNCTION_NAME"
+          exit 1
         fi
-
-      # Empaqueta solo la Lambda indicada
       - cd $LAMBDA_FUNCTION_NAME
       - zip -r ../dist/$LAMBDA_FUNCTION_NAME.zip .
       - cd - > /dev/null
-
       - echo "Contenido final del directorio dist:"
       - ls -R dist
 
